/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\vuepress_project\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1efc24b6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1efc24b6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6b61f839",
    path: "/app%E6%B5%8B%E8%AF%95/app%E6%B5%8B%E8%AF%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b61f839").then(next)
    },
  },
  {
    path: "/app测试/app测试.html",
    redirect: "/app%E6%B5%8B%E8%AF%95/app%E6%B5%8B%E8%AF%95.html"
  },
  {
    path: "/app测试/app测试.html",
    redirect: "/app%E6%B5%8B%E8%AF%95/app%E6%B5%8B%E8%AF%95.html"
  },
  {
    name: "v-035bde23",
    path: "/atlas%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86/atlas%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-035bde23").then(next)
    },
  },
  {
    path: "/atlas元数据管理/atlas元数据管理.html",
    redirect: "/atlas%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86/atlas%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86.html"
  },
  {
    path: "/atlas元数据管理/atlas元数据管理.html",
    redirect: "/atlas%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86/atlas%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86.html"
  },
  {
    name: "v-55e2fce9",
    path: "/ansible/ansible.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55e2fce9").then(next)
    },
  },
  {
    name: "v-6d27022e",
    path: "/azkaban/azkaban.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d27022e").then(next)
    },
  },
  {
    name: "v-065c5929",
    path: "/cypress/cypress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-065c5929").then(next)
    },
  },
  {
    name: "v-067c6d63",
    path: "/clickhouse/clickhouse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-067c6d63").then(next)
    },
  },
  {
    name: "v-2f86c7e3",
    path: "/docker/docker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f86c7e3").then(next)
    },
  },
  {
    name: "v-70103fe3",
    path: "/groovy/groovy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70103fe3").then(next)
    },
  },
  {
    name: "v-319eb969",
    path: "/elk/elk.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-319eb969").then(next)
    },
  },
  {
    name: "v-ea4d912e",
    path: "/flume/flume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea4d912e").then(next)
    },
  },
  {
    name: "v-2276e1a9",
    path: "/flink/flink.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2276e1a9").then(next)
    },
  },
  {
    name: "v-7b2ea03a",
    path: "/impala/impala.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b2ea03a").then(next)
    },
  },
  {
    name: "v-df495b2e",
    path: "/hue/hue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df495b2e").then(next)
    },
  },
  {
    name: "v-0da5083a",
    path: "/hadoop/hadoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0da5083a").then(next)
    },
  },
  {
    name: "v-34525d23",
    path: "/hive/hive.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34525d23").then(next)
    },
  },
  {
    name: "v-142c3be9",
    path: "/hbase/hbase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-142c3be9").then(next)
    },
  },
  {
    name: "v-486171ba",
    path: "/jmeter%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95/jmeter%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-486171ba").then(next)
    },
  },
  {
    path: "/jmeter接口测试/jmeter接口测试.html",
    redirect: "/jmeter%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95/jmeter%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95.html"
  },
  {
    path: "/jmeter接口测试/jmeter接口测试.html",
    redirect: "/jmeter%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95/jmeter%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95.html"
  },
  {
    name: "v-6545f7e3",
    path: "/harbor/harbor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6545f7e3").then(next)
    },
  },
  {
    name: "v-4e2461a9",
    path: "/jvm/jvm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e2461a9").then(next)
    },
  },
  {
    name: "v-a822753a",
    path: "/kubernetes/kubernetes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a822753a").then(next)
    },
  },
  {
    name: "v-0f0ad5ba",
    path: "/java/java.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f0ad5ba").then(next)
    },
  },
  {
    name: "v-59a6ae69",
    path: "/kylin/kylin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59a6ae69").then(next)
    },
  },
  {
    name: "v-153b6b29",
    path: "/kafka/kafka.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-153b6b29").then(next)
    },
  },
  {
    name: "v-38da8cf6",
    path: "/java%E5%A4%9A%E7%BA%BF%E7%A8%8B/java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38da8cf6").then(next)
    },
  },
  {
    path: "/java多线程/java多线程.html",
    redirect: "/java%E5%A4%9A%E7%BA%BF%E7%A8%8B/java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    path: "/java多线程/java多线程.html",
    redirect: "/java%E5%A4%9A%E7%BA%BF%E7%A8%8B/java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    name: "v-791d2f29",
    path: "/oozie/oozie.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-791d2f29").then(next)
    },
  },
  {
    name: "v-9045fe42",
    path: "/pythonUI%E8%87%AA%E5%8A%A8%E5%8C%96/pythonUI%E8%87%AA%E5%8A%A8%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9045fe42").then(next)
    },
  },
  {
    path: "/pythonUI自动化/pythonUI自动化.html",
    redirect: "/pythonUI%E8%87%AA%E5%8A%A8%E5%8C%96/pythonUI%E8%87%AA%E5%8A%A8%E5%8C%96.html"
  },
  {
    path: "/pythonUI自动化/pythonUI自动化.html",
    redirect: "/pythonUI%E8%87%AA%E5%8A%A8%E5%8C%96/pythonUI%E8%87%AA%E5%8A%A8%E5%8C%96.html"
  },
  {
    name: "v-531137e3",
    path: "/python/python.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-531137e3").then(next)
    },
  },
  {
    name: "v-1f3fd2ae",
    path: "/linux/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f3fd2ae").then(next)
    },
  },
  {
    name: "v-c89c8bae",
    path: "/mysql/mysql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c89c8bae").then(next)
    },
  },
  {
    name: "v-91fe55ca",
    path: "/python%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96/python%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91fe55ca").then(next)
    },
  },
  {
    path: "/python接口自动化/python接口自动化.html",
    redirect: "/python%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96/python%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96.html"
  },
  {
    path: "/python接口自动化/python接口自动化.html",
    redirect: "/python%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96/python%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96.html"
  },
  {
    name: "v-a66a572e",
    path: "/redis/redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a66a572e").then(next)
    },
  },
  {
    name: "v-4af87329",
    path: "/scala/scala.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4af87329").then(next)
    },
  },
  {
    name: "v-724e3103",
    path: "/test/test01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-724e3103").then(next)
    },
  },
  {
    name: "v-2ab9c2ba",
    path: "/vuepress/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ab9c2ba").then(next)
    },
  },
  {
    name: "v-1c88a3ae",
    path: "/sqoop/sqoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c88a3ae").then(next)
    },
  },
  {
    name: "v-b474323a",
    path: "/sparkstreaming/sparkstreaming.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b474323a").then(next)
    },
  },
  {
    name: "v-05e15f29",
    path: "/zookeeper/zookeeper.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05e15f29").then(next)
    },
  },
  {
    name: "v-1dd6962e",
    path: "/spark/spark.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dd6962e").then(next)
    },
  },
  {
    name: "v-f382d5fa",
    path: "/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f382d5fa").then(next)
    },
  },
  {
    path: "/性能测试/性能测试.html",
    redirect: "/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95.html"
  },
  {
    path: "/性能测试/性能测试.html",
    redirect: "/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95.html"
  },
  {
    name: "v-bc28d6fa",
    path: "/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84(java)/java%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bc28d6fa").then(next)
    },
  },
  {
    path: "/数据结构(java)/java数据结构.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84(java)/java%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/数据结构(java)/java数据结构.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84(java)/java%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-5a24b923",
    path: "/%E6%95%B0%E4%BB%93%E9%A1%B9%E7%9B%AE/%E6%95%B0%E4%BB%93%E9%A1%B9%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a24b923").then(next)
    },
  },
  {
    path: "/数仓项目/数仓项目.html",
    redirect: "/%E6%95%B0%E4%BB%93%E9%A1%B9%E7%9B%AE/%E6%95%B0%E4%BB%93%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: "/数仓项目/数仓项目.html",
    redirect: "/%E6%95%B0%E4%BB%93%E9%A1%B9%E7%9B%AE/%E6%95%B0%E4%BB%93%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]