name: 'github actions build and deploy gh-pages'
on: 
  push:
    branches:
      - master  // 基于 master 分支，如果你的分支不是这个，请切换
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   // 使用 ubuntu 服务器
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1   
        with: 
          persist-credentials: false
      - name: install and build
        run: |        
          npm install yarn --save-dev
          ./node_modules/yarn/bin/yarn install -D
          ./node_modules/yarn/bin/yarn docs:build
          

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9  // 引用别人的部署插件
        with: 
          ACCESS_TOKEN: ${{ af748f3ef4a8a72679361c8eed4758afd26ddfbf  }}   // 这里需要设置成你的 token
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
